version: '3.4'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:6.0.0
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:6.0.0
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  schema-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:6.0.0
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  producer-avro:
    container_name: producer-avro
    hostname: producer-avro
    image: juliocesarmidia/producer-avro:6.0.0
    build:
      context: .
    restart: "no"
    networks:
      - subnet_0
    environment:
      JAVA_OPTIONS: -Xmx400m
      BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      TOPIC_NAME: customer-avro

  nexus:
    container_name: nexus
    hostname: nexus
    image: sonatype/nexus3
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 9081:8081
    volumes:
      - nexus-data:/nexus-data

networks:
  subnet_0:
    driver: bridge

volumes:
  zookeeper-data: {}
  nexus-data: {}
